apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-overlay
spec:
  selector:
    matchLabels:
      app: curl-overlay
  replicas: 3
  template:
    metadata:
      annotations:
        networking.alibaba.com/network-type: Overlay
      labels:
        app: curl-overlay
    spec:
      containers:
        - args:
            - -c
            - sleep 999999999
          command:
            - /bin/sh
          name: curl
          image: curlimages/curl:latest
